[project]
name = "mtaa-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.8",
]

[dependency-groups]
dev = ["black", "pre-commit"]

[tool.black]
line-length = 90
target-version = ['py310', 'py311', 'py313']
exclude = '''
/(
    .venv
  | env
  | migrations
  | .*\.pyc
)/
'''
