"""change listing schema to not have unique title

Revision ID: 6a9b0da854c0
Revises: 2b964d5af852
Create Date: 2025-04-03 14:13:49.140102

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a9b0da854c0'
down_revision: Union[str, None] = '2b964d5af852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('listings_title_key', 'listings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('listings_title_key', 'listings', ['title'])
    # ### end Alembic commands ###
