"""add constraints to the models

Revision ID: 3d6b489860bd
Revises: f946c3e562fe
Create Date: 2025-03-18 00:58:34.552727

"""

from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3d6b489860bd"
down_revision: Union[str, None] = "f946c3e562fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "listings", ["title"])
    op.alter_column(
        "userReviews", "reviewer_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "userReviews", "reviewee_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        "userReviews_reviewee_id_fkey", "userReviews", type_="foreignkey"
    )
    op.drop_constraint(
        "userReviews_reviewer_id_fkey", "userReviews", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "userReviews", "users", ["reviewee_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "userReviews", "users", ["reviewer_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(
        "userSearchAlerts_user_id_fkey", "userSearchAlerts", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "userSearchAlerts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "userSearchAlerts", type_="foreignkey")
    op.create_foreign_key(
        "userSearchAlerts_user_id_fkey",
        "userSearchAlerts",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "userReviews", type_="foreignkey")
    op.drop_constraint(None, "userReviews", type_="foreignkey")
    op.create_foreign_key(
        "userReviews_reviewer_id_fkey", "userReviews", "users", ["reviewer_id"], ["id"]
    )
    op.create_foreign_key(
        "userReviews_reviewee_id_fkey", "userReviews", "users", ["reviewee_id"], ["id"]
    )
    op.alter_column(
        "userReviews", "reviewee_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "userReviews", "reviewer_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(None, "listings", type_="unique")
    # ### end Alembic commands ###
