"""change offer types to include RENT, BUY, BOTH for better clarity

Revision ID: 3091bbcdeb92
Revises: 13e9db4f4c17
Create Date: 2025-04-05 11:55:27.704722

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3091bbcdeb92'
down_revision: Union[str, None] = '13e9db4f4c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
