"""add active boolean to every watchdog

Revision ID: 7c78c1568e15
Revises: 7b0384b476dd
Create Date: 2025-04-13 22:32:17.200881

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c78c1568e15'
down_revision: Union[str, None] = '7b0384b476dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userSearchAlerts', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userSearchAlerts', 'is_active')
    # ### end Alembic commands ###
