"""listing status: add rented listing status

Revision ID: 1489ebf4bea4
Revises: 139101757380
Create Date: 2025-04-10 22:25:52.597274

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1489ebf4bea4"
down_revision: Union[str, None] = "139101757380"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    # ### end Alembic commands ###
    op.execute("ALTER TYPE listingstatus ADD VALUE 'RENTED' AFTER 'REMOVED'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("secret_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("date_formed", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("asd", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="product_pkey"),
    )
    # ### end Alembic commands ###
