"""Add date_formed field to the Product Base model

Revision ID: 1cf961f73255
Revises: ab7bcaa079a8
Create Date: 2025-03-01 15:58:23.667882

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cf961f73255"
down_revision: Union[str, None] = "ab7bcaa079a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("date_formed", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "date_formed")
    # ### end Alembic commands ###
