"""add unique id to sale listings

Revision ID: 24388072986c
Revises: 3d6b489860bd
Create Date: 2025-03-20 22:23:55.140489

"""

from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "24388072986c"
down_revision: Union[str, None] = "3d6b489860bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rentListings",
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("renter_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["renter_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("listing_id", "renter_id"),
    )
    op.create_table(
        "saleListings",
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("buyer_id", sa.Integer(), nullable=False),
        sa.Column("sold_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("listing_id", "buyer_id"),
        sa.UniqueConstraint("listing_id"),
    )
    op.drop_constraint("listings_buyer_id_fkey", "listings", type_="foreignkey")
    op.drop_column("listings", "buyer_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listings",
        sa.Column("buyer_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "listings_buyer_id_fkey", "listings", "users", ["buyer_id"], ["id"]
    )
    op.drop_table("saleListings")
    op.drop_table("rentListings")
    # ### end Alembic commands ###
