"""change listing schema

Revision ID: 2b964d5af852
Revises: 7595325323c3
Create Date: 2025-04-03 14:12:12.368971

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b964d5af852'
down_revision: Union[str, None] = '7595325323c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'listings', ['title'])
    op.drop_column('listings', 'visibility')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('visibility', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'listings', type_='unique')
    op.alter_column('listings', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
