name: Run Pytest

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
on: [push]

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest
    
    env:
      TESTING: "1"
      DB_USER: "test"
      DB_PASSWORD: "test"
      DB_NAME: "test"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Run tests
        run: uv run pytest
